@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueDisplayableList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueDisplayableList
UniqueTagList -[hidden]down- UniqueDisplayableList

UniqueTagList -right-> "*" Tag
UniqueDisplayableList -right-> Seller

Seller *--> Address
Seller *--> HouseInfo
Seller -up-> "*" Tag
Person ..up.> Seller
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
@enduml
