@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteSellerCommandParser" as DeleteSellerCommandParser LOGIC_COLOR
participant "d:DeleteSellerCommand" as DeleteSellerCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("sdelete 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("sdelete 1")
activate AddressBookParser

create DeleteSellerCommandParser
AddressBookParser -> DeleteSellerCommandParser
activate DeleteSellerCommandParser

DeleteSellerCommandParser --> AddressBookParser
deactivate DeleteSellerCommandParser

AddressBookParser -> DeleteSellerCommandParser : parse("1")
activate DeleteSellerCommandParser

create DeleteSellerCommand
DeleteSellerCommandParser -> DeleteSellerCommand
activate DeleteSellerCommand

DeleteSellerCommand --> DeleteSellerCommandParser : d
deactivate DeleteSellerCommand

DeleteSellerCommandParser --> AddressBookParser : d
deactivate DeleteSellerCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteSellerCommandParser -[hidden]-> AddressBookParser
destroy DeleteSellerCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteSellerCommand : execute()
activate DeleteSellerCommand

DeleteSellerCommand -> Model : deleteSeller(1)
activate Model

Model --> DeleteSellerCommand
deactivate Model

create CommandResult
DeleteSellerCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteSellerCommand
deactivate CommandResult

DeleteSellerCommand --> LogicManager : result
deactivate DeleteSellerCommand

[<--LogicManager
deactivate LogicManager
@enduml
