@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":EditBuyerCommandParser" as EditBuyerCommandParser LOGIC_COLOR
participant "ebd:EditBuyerDescriptor" as EditBuyerDescriptor LOGIC_COLOR
participant ":EditBuyerCommand" as EditBuyerCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":Storage" as Storage MODEL_COLOR
end box

[-> LogicManager : execute(bedit 2 n/John)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(bedit 2 n/John)
activate AddressBookParser

create EditBuyerCommandParser
AddressBookParser -> EditBuyerCommandParser
activate EditBuyerCommandParser

EditBuyerCommandParser --> AddressBookParser
deactivate EditBuyerCommandParser

AddressBookParser --> EditBuyerCommandParser : parse(1 n/John)
activate EditBuyerCommandParser

create EditBuyerDescriptor
EditBuyerCommandParser --> EditBuyerDescriptor
activate EditBuyerDescriptor

EditBuyerDescriptor --> EditBuyerCommandParser
deactivate EditBuyerDescriptor

EditBuyerCommandParser --> EditBuyerDescriptor
activate EditBuyerDescriptor

EditBuyerDescriptor --> EditBuyerCommandParser : ebd
deactivate EditBuyerDescriptor

create EditBuyerCommand
EditBuyerCommandParser --> EditBuyerCommand : ebd
activate EditBuyerCommand

EditBuyerCommand --> EditBuyerCommandParser : command
deactivate EditBuyerCommand

EditBuyerCommandParser --> AddressBookParser : command
deactivate EditBuyerCommandParser

AddressBookParser --> LogicManager : command
deactivate AddressBookParser

LogicManager -> EditBuyerCommand : execute()
activate EditBuyerCommand

EditBuyerCommand --> Model : setBuyer(old, new)
activate Model

Model --> EditBuyerCommand
deactivate Model

create CommandResult
EditBuyerCommand -> CommandResult
activate CommandResult

CommandResult --> EditBuyerCommand
deactivate CommandResult

EditBuyerCommand --> LogicManager : result
deactivate EditBuyerCommand

LogicManager -> Storage : saveAddressBook(curAddressBook)
activate Storage

Storage --> LogicManager
deactivate Storage





[<--LogicManager
deactivate LogicManager
@enduml
