@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "warn:CommandWarnings" as warn LOGIC_COLOR
participant ":AddBuyerCommandParser" as AddBuyerCommandParser LOGIC_COLOR
participant ":AddBuyerCommand" as AddBuyerCommand LOGIC_COLOR
participant "<<class>>\nParseUtil" as ParseUtil LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "<<class>>\nName" as NameClass MODEL_COLOR
participant ":Name" as Name MODEL_COLOR
end box

[-> AddressBookParser : parseCommand("buyer n/毛泽东" p/...)
activate AddressBookParser
create warn
AddressBookParser -> warn : new CommandWarnings()

activate warn
warn --> AddressBookParser
deactivate warn
AddressBookParser --> AddressBookParser : parseCommand("buyer...", warn)
activate AddressBookParser
create AddBuyerCommandParser
AddressBookParser -> AddBuyerCommandParser : new AddBuyerCommandParser()
activate AddBuyerCommandParser
AddBuyerCommandParser --> AddressBookParser
deactivate AddBuyerCommandParser
AddressBookParser -> AddBuyerCommandParser : parse("n/毛泽东...", warn)
activate AddBuyerCommandParser
AddBuyerCommandParser -> ParseUtil : parseName("毛泽东")
activate ParseUtil
ParseUtil -> NameClass : isValidName("毛泽东")
activate NameClass
NameClass --> ParseUtil : true
deactivate NameClass
ParseUtil -> NameClass : isAppropriateName("毛泽东")
activate NameClass
NameClass --> ParseUtil : false
deactivate NameClass
ParseUtil -> warn : AddWarning(MESSAGE_RECOMMENDATIONS)
activate warn
warn --> ParseUtil
deactivate warn
create Name
ParseUtil -> Name : new Name("毛泽东")
activate Name
Name --> ParseUtil
deactivate Name
ParseUtil --> AddBuyerCommandParser
deactivate ParseUtil
create AddBuyerCommand
AddBuyerCommandParser -> AddBuyerCommand : new AddBuyerCommand(Buyer buyer, warn)
activate AddBuyerCommand
AddBuyerCommand --> AddBuyerCommandParser
deactivate AddBuyerCommand
AddBuyerCommandParser --> AddressBookParser
deactivate AddBuyerCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.'
AddressBookParser -[hidden]-> AddressBookParser
destroy AddBuyerCommandParser
[<-- AddressBookParser
deactivate AddressBookParser
deactivate AddressBookParser
[-> AddBuyerCommand : execute()
activate AddBuyerCommand
AddBuyerCommand -> warn : getWarningMessages()
activate warn
warn --> AddBuyerCommand
deactivate warn
[<-- AddBuyerCommand : A CommandResult containing a warning message.
deactivate AddBuyerCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.'
AddressBookParser -[hidden]-> AddressBookParser
destroy AddBuyerCommand

@enduml
